apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.appName }}-deployment
  labels:
    app: {{ .Values.backend.appName }}
spec:
  replicas: {{ .Values.backend.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: {{ .Values.backend.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.appName }}
    spec:
      containers:
        - name: {{ .Values.backend.appName }}
          image: {{ .Values.backend.container.registry }}/{{ .Values.backend.container.image }}:{{ .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}
          {{- if .Values.backend.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.livenessProbe.path }}
              port: {{ .Values.backend.livenessProbe.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          {{- end }}
          {{- if .Values.backend.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.readinessProbe.path }}
              port: {{ .Values.backend.readinessProbe.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          {{- if .Values.backend.envSecretName }}
          envFrom:
            - secretRef:
                name: {{ .Values.backend.envSecretName }}
          {{- end }}
      {{- if .Values.backend.container.useRegistrySecret }}
      imagePullSecrets:
        - name: {{ .Values.backend.container.registrySecret }}
      {{- end }}
