apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "joyforum.fullname" . }}
  labels:
    {{- include "joyforum.labels" . | nindent 4 }}
spec:
  # If autoscaling is on, we let HPA control replicas, not this hardcoded number
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "joyforum.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "joyforum.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: wordpress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: WORDPRESS_DB_NAME
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_CONFIG_EXTRA
              value: {{ .Values.wordpress.configExtra | quote }}
          # UPDATED: Added resources for HPA
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # UPDATED: Added volume mount
          volumeMounts:
            - name: wp-data
              mountPath: /var/www/html/wp-content
      volumes:
        - name: wp-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "joyforum.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}