apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "joyforum.fullname" . }}
  labels:
    {{- include "joyforum.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "joyforum.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "joyforum.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      # Sets group ownership to www-data
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      
      # NEW: Init Container to ensure Azure File permissions are correct before WP starts
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 33:33 /var/www/html/wp-content/uploads && chmod -R 775 /var/www/html/wp-content/uploads"]
          # volumeMounts:
          #   - name: wp-data
          #     mountPath: {{ .Values.persistence.mountPath }}

      containers:
        - name: wordpress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: WORDPRESS_DB_NAME
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secret
                  key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_CONFIG_EXTRA
              value: {{ .Values.wordpress.configExtra | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # volumeMounts:
          #   - name: wp-data
          #     mountPath: {{ .Values.persistence.mountPath }}
      # volumes:
      #   - name: wp-data
      #     {{- if .Values.persistence.enabled }}
      #     persistentVolumeClaim:
      #       claimName: {{ include "joyforum.fullname" . }}-pvc
      #     {{- else }}
      #     emptyDir: {}
      #     {{- end }}
