apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.appName }}-deployment
  labels:
    app: {{ .Values.frontend.appName }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.appName }}
    spec:
      containers:
      - name: {{ .Values.frontend.appName }}
        image: {{ .Values.frontend.container.registry }}/{{ .Values.frontend.container.image }}:{{ .Chart.AppVersion }}
        ports:
        - containerPort: {{ .Values.frontend.service.targetPort }}
      {{- if .Values.frontend.container.useRegistrySecret }}
      imagePullSecrets:
      - name: {{ .Values.frontend.container.registrySecret }}
      {{- end }}
