apiVersion: v1
kind: Service
metadata:
  name: {{ include "joyforum.fullname" . }}
  labels:
    app: {{ include "joyforum.name" . }}
    {{- include "joyforum.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: {{ include "joyforum.name" . }}
